# Generated by Django 4.2.4 on 2024-06-26 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grocery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='Автор рецепта'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='grocery.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcategories', to='grocery.subcategory', verbose_name='Подкатегория '),
        ),
        migrations.AddConstraint(
            model_name='shoppingcartproducts',
            constraint=models.UniqueConstraint(fields=('shopping_cart', 'product'), name='unique_shopping_cart_product', violation_error_message='Товар уже есть в корзине!'),
        ),
    ]
